name: Switchres CI

on: [push, pull_request]

jobs:
  linux-build-standalone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install libxrandr-dev libdrm-dev
    - name: make
      run: make
    - name: Prepare artifacts
      run: mkdir artifacts && cp switchres{,.ini} artifacts/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: switchres linux binary
        path: artifacts/

  linux-build-lib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install libxrandr-dev libdrm-dev
    - name: make
      run: make libswitchres
    - name: Prepare artifacts
      run: mkdir artifacts && cp libswitchres.{so,a} artifacts/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: switchres linux lib
        path: artifacts/

  win32-build-x86_64-standalone:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_mingw
      run: sudo apt-get install mingw-w64
    - name: posix_model_x86_64
      run: sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
    - name: make
      run: make PLATFORM=NT CROSS_COMPILE=x86_64-w64-mingw32-
    - name: Prepare artifacts
      run: mkdir artifacts && cp switchres.{exe,ini} artifacts/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: switchres win32 x86_64 binary
        path: artifacts/

  win32-build-x86_64-lib:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_mingw
      run: sudo apt-get install mingw-w64
    - name: posix_model_x86_64
      run: sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
    - name: make
      run: make PLATFORM=NT CROSS_COMPILE=x86_64-w64-mingw32- libswitchres
    - name: Prepare artifacts
      run: mkdir artifacts && cp libswitchres.{dll,lib} artifacts/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: switchres win32 x86_64 lib
        path: artifacts/

  win32-build-i686-standalone:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_mingw
      run: sudo apt-get install mingw-w64
    - name: posix_model_i686
      run: sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix
    - name: make
      run: make PLATFORM=NT CROSS_COMPILE=i686-w64-mingw32-
    - name: Prepare artifacts
      run: mkdir artifacts && cp switchres.{exe,ini} artifacts/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: switchres win32 i686 binary
        path: artifacts/

  win32-build-i686-lib:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_mingw
      run: sudo apt-get install mingw-w64
    - name: posix_model_i686
      run: sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix
    - name: make
      run: make PLATFORM=NT CROSS_COMPILE=i686-w64-mingw32- libswitchres
    - name: Prepare artifacts
      run: mkdir artifacts && cp libswitchres.{dll,lib} artifacts/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: switchres win32 i686 lib
        path: artifacts/

